module.exports = {
  apps: [
    {
      name: 'sniper-bot',
      cwd: '/opt/claude/solana-sniper-bot/bot',
      script: 'npx',
      args: 'ts-node src/index.ts',
      interpreter: 'none',
      env: { NODE_ENV: 'production' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: '/opt/claude/solana-sniper-bot/logs/bot.out.log',
      error_file: '/opt/claude/solana-sniper-bot/logs/bot.err.log',
    },
    {
      name: 'sniper-dashboard',
      cwd: '/opt/claude/solana-sniper-bot/dashboard',
      script: 'npx',
      args: 'next start -p 3000',
      interpreter: 'none',
      env: { NODE_ENV: 'production' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: '/opt/claude/solana-sniper-bot/logs/dashboard.out.log',
      error_file: '/opt/claude/solana-sniper-bot/logs/dashboard.err.log',
    },
  ],
};
